import type {NextPage} from 'next'
import Head from 'next/head'
import {Box, Center, Flex, Text} from "@chakra-ui/react";
import ActionModal from "../components/ActionModal/ActionModal";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Link Shortener App | Shorten</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Center minH={'100vh'} bg={'cyan.50'}>
                <Flex direction={'column'} justifyContent={'center'} alignItems={"center"}>
                    <Box pb={8}>
                        <Text fontSize={'3xl'}>
                            Shorten your link with ease
                        </Text>
                    </Box>
                    <Box>
                        <ActionModal />
                    </Box>
                </Flex>
            </Center>

        </>
    )
}

export default Home
